### PR TITLE
Recipe list

### LINKED ISSUE #3: [8pts] Create the recipes list
- Should display a list of recipes created by the logged-in user as in the wireframe.
- Should lead to recipe details.
- If the user is the owner of the recipe, should allow user to delete it.

### LINKED ISSUE #5: [6pts] Create recipe details
- If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
- If the user is the owner of the recipe, should lead to the form that allows user to add new food.

### PR DESCRIPTION
**Pull request by joskalenda**
# Hey Billions, please have a look at this PR, 

### Features 

- [ ]  Create new recipe ✅ 

- [ ]  List all recipes of the user ✅ 

- [ ]  Create recipe details ✅

### CODE REVIEW

**Review by billionsjoel — CHANGES_REQUESTED** [review]
Hello @joskalenda , 

♻️  Good job so far with the project 👍 , however, i can not proceed to review your project because the routes still have some issues.
 

1. [ ] The '/recipes' route gives me this error

 
Screenshot 2022-05-17 at 16 55 57

2.  - [ ] Kindly show user understandable error incase a recipe is not found. I think that would be a better way to approach error handling.

Screenshot 2022-05-17 at 17 00 20

3. The Create new recipe is working fine. 👍 
Screenshot 2022-05-17 at 17 01 49

4. - [ ] I get this error when i try adding a new recipe.

Screenshot 2022-05-17 at 17 03 26

-------------------------------
 Can't wait to see the new changes you have implemented.
 
 
 -------------------------------------

**Comment by joskalenda** [comment]
Oh, this did not display in my local, but let me fix it once at all.
Thanks for mentioning @billionsjoel

**Comment by joskalenda** [comment]
@billionsjoel  You can check again and see if the error is fixed

**Review by billionsjoel — APPROVED** [review]
Hi @joskalenda 

Good job finishing this task, there is nothing else i can say except it is time to merge it. :shipit: 
Congratulations.

**Comment by joskalenda** [comment]
@billionsjoel, Thank you

**Pull request merged**
